name: Python package

on: push

jobs:
  build_wheels:
    strategy:
      matrix:
        plat:
          - [ ubuntu-latest, "3.x" ]
          - [ ubuntu-18.04, "3.6" ]
          - [ ubuntu-20.04, "3.8" ]
          - [ ubuntu-22.04, "3.10" ]
          - [ ubuntu-24.04, "3.12" ]
          - [ windows-latest, "3.x" ]
          - [ windows-latest, "3.6" ]
          - [ windows-latest, "3.8" ]
          - [ windows-latest, "3.10" ]
          - [ windows-latest, "3.12" ]
    name: Build binary distribution
    runs-on: ${{ matrix.plat[0] }}
    steps:
      - uses: actions/checkout@v4
      - if: ${{ startsWith(matrix.plat[0], 'ubuntu') }}
        run: sudo apt update && sudo apt install -y libudev-dev
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.plat[1] }}
      - run: |
          python -m pip install build
          python -m build --wheel
      - uses: actions/upload-artifact@v4
        with:
          name: output-wheel-${{ matrix.plat[0] }}-${{ matrix.plat[1] }}
          path: dist/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pipx run build --sdist
      - uses: actions/upload-artifact@v4
        with:
          name: output-sdist
          path: dist/*.tar.gz
